name: usefast
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.0+1
  fl_chart: ^0.40.6
  animate_do: ^2.0.0
  get: ^4.6.5
  flutterwave_standard: 1.0.8

  datetime_picker_formfield_new: ^2.1.0
  file_picker: ^5.3.2
  bootstrap_alert: ^1.0.1
  dio: ^5.3.2
  currency_symbols: ^0.0.1+2
  simple_currency_format: ^1.0.7
  image_picker: ^1.0.4
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.16
  emoji_picker_flutter: ^1.5.2
  url_launcher: ^6.1.8
  loading_animation_widget: ^1.2.0+4
  cached_network_image: ^3.2.3
  card_loading: ^0.2.2
  flutter_phoenix: ^1.1.0
  panara_dialogs: ^0.1.4
  giff_dialog: ^1.0.1
  intl: ^0.17.0
  flutter_awesome_select: ^6.5.0

  flutter_awesome_bottom_sheet: ^0.0.2
  flutter_tawk: ^0.1.0
  crisp_chat: ^0.0.4
  flutter_native_contact_picker: ^0.0.5
  icons_plus: ^4.0.0
  uuid: ^4.2.1
  fancy_flutter_dialog: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  sliding_sheet2: ^2.0.1
  local_auth: ^2.1.7
  flutter_otp_text_field: ^1.1.1
  h3m_shimmer_card: ^0.0.2
  giffy_dialog: ^2.0.0+2
  loading_overlay_pro: ^2.1.1

dependency_overrides:
#  flutter_svg: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true



  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay-Medium.otf
        - asset: assets/fonts/SFUIDisplay-Bold.otf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf